[package]
name = "topgrade"
description = "Upgrade all the things"
license-file = "LICENCE"
repository = "https://github.com/r-darwish/topgrade"
version = "0.2.0"
authors = ["Roey Darwish Dror <roey.ghost@gmail.com>"]
exclude = ["doc/screenshot.gif"]

[dependencies]
which = "2.0.0"
error-chain = "0.11.0"
os_type = "2.0.0"
termion = "1.5.1"
